---

version: "3.7"

services:
  go:
    working_dir: /go/src/sunabako
    command: bash
    tty: true
    build:
      context: ../
      dockerfile: golang/Dockerfile
      args:
        TAG: ${GO_VERSION_TAG:-1.13-buster}
    volumes:
      - ../golang/src:/go/src/sunabako
    links:
      - mq
